server:
  port: 9527

spring:
  application:
    name: "cloud-gateway"
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service            #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-03-10T16:48:03.598220800+08:00[Asia/Shanghai]
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Query=username, \d+
            #- Method=GET #请求方法要大写
            #- My=moxixun

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service            #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
            - After=2024-03-10T16:48:03.598220800+08:00[Asia/Shanghai]
            - Cookie=username,moxixun

        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            #- Path=/aaa/bbb/{segment}
             - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
            #- Path=/gateway/filter/**              # 断言，为配合PrefixPath测试过滤，暂时注释掉/pay
          filters:
             - My=moxixun
             #- RedirectTo=302, http://www.atguigu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/
             #- SetPath=/pay/gateway/{segment}
             #- PrefixPath=/pay # http://localhost:9527/pay/gateway/filter 隐藏了我们的真实地址
             # - AddRequestHeader=X-Request-atguigu1,atguiguValue1  #请求头kv，若一头含有多参则重写一行设置
             # - AddRequestHeader=X-Request-atguigu2,atguiguValue2
             # - RemoveRequestHeader=sec-fetch-site                 #移除请求头k为sec-fetch-site的
             # - SetRequestHeader=sec-fetch-user, moxixun           #修改请求头k为sec-fetch-user的值为moxixun
             # - AddRequestParameter=customerId, 036233            #添加请求参数
             # - RemoveRequestParameter=customerName               #移除请求参数
             # - AddResponseHeader=X-Response-moxixun, 036233 # 新增请求参数X-Response-moxixun, 值为036233
             # - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
             # - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除